name: Extract stunnel Archive

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Обеспечивает права на запись

      - name: Extract stunnel-5.74.tar.gz into the repository
        run: |
          ARCHIVE="stunnel-5.74.tar.gz"

          # Check if archive exists
          if [ ! -f "$ARCHIVE" ]; then
            echo "Archive $ARCHIVE not found in the repository."
            exit 1
          fi

          ROOT_DIR=$(tar -tf $ARCHIVE | head -1 | cut -f1 -d"/")

          # Check if the root directory in the archive contains the sources
          if tar -tf $ARCHIVE | grep -q "${ROOT_DIR}/src"; then
            echo "The archive contains the source directory, extracting only the contents of ${ROOT_DIR}."
            tar -xzf $ARCHIVE --strip-components=1 -C .
          else
            echo "The archive does not contain the source directory, extracting as is."
            tar -xzf $ARCHIVE -C .
          fi

          # List the extracted files for verification
          echo "Extracted files:"
          ls -la .

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Extracted stunnel-5.74.tar.gz"

          git push https://x-access-token:$TOKEN@github.com/madfixed/stunnel5x.git
